# inherit_from: .rubocop_todo.yml

# rubocop --auto-gen-config
# rubocop
# rubocop:disable all

#inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'

    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.rb'
    - 'test/**/*.rb'   # 581 offenses
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
#    - '**/Rakefile'

#AllCops:
#  Exclude:
#    - 'db/**/*'
#    - 'config/**/*'
#    - 'script/**/*'
#    - 'bin/{rails,rake}'
#    - 'spec/**/*'
#    - !ruby/regexp /old_and_unused\.rb$/

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/IndentFirstArrayElement:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/Tab:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WhenThen:
  Exclude:
    - '.watchr'




